import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { returnRequests, orders, payments, shipmentAuditLogs } from "@/db/schema";
import { eq } from "drizzle-orm";
import { authorize } from "@/middleware/auth";
import { nanoid } from "nanoid";
import { getPaymentProvider } from "@/lib/payments/payment-factory";

/**
 * POST /api/admin/returns/[id]/generate-payment-link
 * Admin endpoint to generate a Razorpay Payment Link for collecting Return/Replacement customer fee.
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await authorize(req, "admin");
    if (!auth.authorized || !auth.user) {
      return auth.response || NextResponse.json(
        { error: "Forbidden: Admin access required." },
        { status: 403 }
      );
    }

    const { id: requestId } = await params;
    if (!requestId) {
      return NextResponse.json({ error: "Return request ID is required" }, { status: 400 });
    }

    const returnReq = await db.query.returnRequests.findFirst({
      where: eq(returnRequests.id, requestId),
      with: {
        order: {
          with: {
            addresses: true,
            user: true,
          },
        },
      },
    });

    if (!returnReq) {
      return NextResponse.json({ error: "Return or replacement request not found" }, { status: 404 });
    }

    if (returnReq.paymentResponsibility !== "CUSTOMER_PAYS") {
      return NextResponse.json(
        { error: "Payment responsibility is not CUSTOMER_PAYS for this request." },
        { status: 400 }
      );
    }

    if (returnReq.paymentStatus === "PAID") {
      return NextResponse.json(
        { error: "Payment has already been recorded as PAID for this request." },
        { status: 400 }
      );
    }

    const amountToPay = returnReq.paymentAmount;
    if (!amountToPay || amountToPay <= 0) {
      return NextResponse.json(
        { error: "Return request payment amount must be greater than zero." },
        { status: 400 }
      );
    }

    // Instantiate payment provider and generate payment session
    const provider = getPaymentProvider();
    const session = await provider.createPayment(returnReq.orderId, amountToPay);

    const paymentRecordId = `pmt_${nanoid(12)}`;
    const purpose = returnReq.type === "RETURN" ? "return_fee" : "replacement_fee";

    await db.insert(payments).values({
      id: paymentRecordId,
      orderId: returnReq.orderId,
      gateway: session.gateway || "razorpay",
      gatewayTransactionId: session.gatewayOrderId || session.id,
      purpose,
      status: "pending",
      amount: amountToPay,
      currency: session.currency || "INR",
      createdAt: new Date(),
    });

    const host = req.headers.get("host") || "localhost:3000";
    const protocol = req.headers.get("x-forwarded-proto") || (host.includes("localhost") ? "http" : "https");
    const baseUrl = `${protocol}://${host}`;

    const paymentLinkUrl = session.paymentUrl || `${baseUrl}/account/orders/${returnReq.orderId}?pay_return_fee=${returnReq.id}`;

    // Prepare WhatsApp customer text
    const customerPhone = returnReq.order?.user?.phoneNumber || returnReq.order?.addresses?.find((a) => a.type === "shipping")?.phone || "";
    const customerName = returnReq.order?.user?.name || returnReq.order?.addresses?.find((a) => a.type === "shipping")?.name || "Customer";
    const amountRupees = (amountToPay / 100).toFixed(2);
    const requestTypeName = returnReq.type === "RETURN" ? "return pickup" : "replacement exchange";

    const whatsappMessage = `Hi ${customerName}, please complete your ${requestTypeName} fee payment of ₹${amountRupees} for Order #${returnReq.orderId}: ${paymentLinkUrl}`;

    // Log shipment audit log
    await db.insert(shipmentAuditLogs).values({
      id: `log_${nanoid(12)}`,
      shipmentId: null,
      orderId: returnReq.orderId,
      adminId: auth.user.id,
      adminName: auth.user.name || auth.user.phoneNumber || "Admin",
      action: "RETURN_PAYMENT_LINK_GENERATED",
      previousState: JSON.stringify({ paymentStatus: returnReq.paymentStatus }),
      newState: JSON.stringify({ paymentStatus: "PENDING", gatewayOrderId: session.gatewayOrderId || session.id }),
      notes: `Razorpay payment link generated by admin for ${returnReq.type} fee of ₹${amountRupees}.`,
    });

    return NextResponse.json({
      success: true,
      paymentLinkUrl,
      customerPhone,
      whatsappMessage,
      amount: amountToPay,
      amountRupees: amountToPay / 100,
      currency: session.currency || "INR",
      gatewayOrderId: session.gatewayOrderId || session.id,
    }, { status: 200 });
  } catch (error: any) {
    console.error("POST /api/admin/returns/[id]/generate-payment-link error:", error);
    return NextResponse.json(
      { error: "Internal Server Error", details: error.message || String(error) },
      { status: 500 }
    );
  }
}
