import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { orders, payments, orderStatusHistory } from "@/db/schema";
import { eq } from "drizzle-orm";
import { authorize } from "@/middleware/auth";
import { nanoid } from "nanoid";
import { getPaymentProvider } from "@/lib/payments/payment-factory";

/**
 * POST /api/admin/orders/[id]/generate-payment-link
 * Admin endpoint to generate a Razorpay Payment Link for collecting pending shipping rate differences.
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await authorize(req, "admin");
    if (!auth.authorized || !auth.user) {
      return auth.response || NextResponse.json(
        { error: "Forbidden: Admin access required." },
        { status: 403 }
      );
    }

    const { id: orderId } = await params;
    if (!orderId) {
      return NextResponse.json({ error: "Order ID is required" }, { status: 400 });
    }

    const order = await db.query.orders.findFirst({
      where: eq(orders.id, orderId),
    });

    if (!order) {
      return NextResponse.json({ error: "Order not found" }, { status: 404 });
    }

    if (order.shippingDifferenceStatus !== "pending") {
      return NextResponse.json(
        { error: "No pending shipping adjustment payment required for this order." },
        { status: 400 }
      );
    }

    const differenceToPay = order.shippingDifference - order.shippingDifferencePaid;
    if (differenceToPay <= 0) {
      return NextResponse.json(
        { error: "Shipping difference amount must be greater than zero." },
        { status: 400 }
      );
    }

    // Instantiate payment provider and generate payment session/order
    const provider = getPaymentProvider();
    const session = await provider.createPayment(orderId, differenceToPay);

    const paymentRecordId = `pmt_${nanoid(12)}`;
    await db.insert(payments).values({
      id: paymentRecordId,
      orderId: order.id,
      gateway: session.gateway || "razorpay",
      gatewayTransactionId: session.gatewayOrderId || session.id,
      purpose: "shipping_adjustment",
      status: "pending",
      amount: differenceToPay,
      currency: session.currency || "INR",
      createdAt: new Date(),
    });

    const host = req.headers.get("host") || "localhost:3000";
    const protocol = req.headers.get("x-forwarded-proto") || (host.includes("localhost") ? "http" : "https");
    const baseUrl = `${protocol}://${host}`;
    
    // Physical link format for direct sharing
    const paymentLinkUrl = session.paymentUrl || `${baseUrl}/account/orders/${orderId}?pay_difference=true`;

    await db.insert(orderStatusHistory).values({
      id: `osh_${nanoid(10)}`,
      orderId,
      status: order.status,
      notes: `Razorpay payment link generated by admin (${auth.user.name || "Admin"}) for pending shipping difference of ₹${(differenceToPay / 100).toFixed(2)}.`,
      createdAt: new Date(),
    });

    return NextResponse.json({
      success: true,
      paymentLinkUrl,
      amount: differenceToPay,
      amountRupees: differenceToPay / 100,
      currency: session.currency || "INR",
      gatewayOrderId: session.gatewayOrderId || session.id,
    }, { status: 200 });

  } catch (error: any) {
    console.error("POST /api/admin/orders/[id]/generate-payment-link error:", error);
    return NextResponse.json(
      { error: "Internal Server Error", details: error.message || String(error) },
      { status: 500 }
    );
  }
}
